// Lobby schema — the durable, seq-ordered side of the system.
//
// Design notes that matter:
//
// 1. ONE ordering authority. Every durable write takes a number from a single
//    counter (`counters.seq`) and stamps it on its own row. Clients hold a
//    `lastSeq` and ask for everything above it, so a reconnecting browser, a
//    resuming monitor and an MCP delta read all index off the same cursor.
//    No gaps, no duplicates, and timeline replay comes almost free.
//
// 2. Ephemeral state is NOT here. Cursors, viewports, selections and typing
//    indicators run 20-30Hz per user and live in memory only (see presence.ts).
//    The previous design wrote cursor x/y into a SQLite table on every move,
//    which is a write storm at cursor frequency.
//
// 3. Tombstones, never hard deletes. A laggy client that has not yet seen a
//    delete will happily re-broadcast the object and resurrect it. Tombstones
//    also keep replay honest and leave a place to implement erasure later —
//    retrofitting deletion into an append-only store is brutal.

import type { Database } from 'bun:sqlite';

export function initSchema(db: Database): void {
  // ---- seq counter -------------------------------------------------------
  db.exec(`
    CREATE TABLE IF NOT EXISTS counters (
      name  TEXT PRIMARY KEY,
      value INTEGER NOT NULL
    )
  `);

  // ---- canvas objects ----------------------------------------------------
  // THE model change: an object is an *artifact*, not an agent. One row per
  // thing on the board — a rendered event, a sticky note, a frame, a pen
  // stroke — each independently movable, groupable and annotatable.
  // NOTE the composite primary key. `id` alone was wrong: ids are generated by
  // clients, every query scopes by (lobby_id, id), and a global PK meant an id
  // used in one lobby permanently blocked that id in every other lobby. That is
  // both a correctness bug (insert fails with a constraint error) and a leak —
  // a client could probe for the existence of ids in lobbies it cannot read.
  db.exec(`
    CREATE TABLE IF NOT EXISTS canvas_objects (
      id            TEXT NOT NULL,
      lobby_id      TEXT NOT NULL,
      type          TEXT NOT NULL,
      event_id      INTEGER,
      parent_id     TEXT,
      x             REAL NOT NULL DEFAULT 0,
      y             REAL NOT NULL DEFAULT 0,
      w             REAL NOT NULL DEFAULT 320,
      h             REAL NOT NULL DEFAULT 200,
      z             INTEGER NOT NULL DEFAULT 0,
      rotation      REAL NOT NULL DEFAULT 0,
      props         TEXT,
      version       INTEGER NOT NULL DEFAULT 1,
      version_nonce INTEGER NOT NULL DEFAULT 0,
      created_by    TEXT,
      updated_by    TEXT,
      updated_at    INTEGER NOT NULL,
      deleted       INTEGER NOT NULL DEFAULT 0,
      seq           INTEGER NOT NULL,
      -- Short per-lobby address ("a7"). Bots refer to artifacts by handle, never
      -- by uuid and never by coordinates, so a reference survives a human
      -- dragging the card somewhere else.
      handle        TEXT,
      -- Caller-supplied idempotency key. Agents retry on any network blip, and
      -- without this a flaky connection silently doubles every artifact.
      idem_key      TEXT,
      PRIMARY KEY (lobby_id, id)
    )
  `);
  rebuildCanvasObjectsPkIfNeeded(db);
  db.exec('CREATE INDEX IF NOT EXISTS idx_co_lobby_seq  ON canvas_objects(lobby_id, seq)');
  db.exec('CREATE INDEX IF NOT EXISTS idx_co_lobby_bbox ON canvas_objects(lobby_id, x, y)');
  db.exec('CREATE INDEX IF NOT EXISTS idx_co_event      ON canvas_objects(event_id)');
  db.exec('CREATE INDEX IF NOT EXISTS idx_co_parent     ON canvas_objects(parent_id)');

  // ---- members (auth lands on this in 1c) --------------------------------
  db.exec(`
    CREATE TABLE IF NOT EXISTS members (
      id           INTEGER PRIMARY KEY AUTOINCREMENT,
      lobby_id     TEXT NOT NULL,
      user_id      TEXT NOT NULL,
      display_name TEXT,
      color        TEXT,
      role         TEXT NOT NULL DEFAULT 'editor',
      token_hash   TEXT,
      token_prefix TEXT,
      created_at   INTEGER NOT NULL,
      last_seen    INTEGER,
      revoked      INTEGER NOT NULL DEFAULT 0,
      UNIQUE(lobby_id, user_id)
    )
  `);
  db.exec('CREATE INDEX IF NOT EXISTS idx_members_lobby  ON members(lobby_id)');
  db.exec('CREATE INDEX IF NOT EXISTS idx_members_prefix ON members(token_prefix)');

  // ---- room chat ---------------------------------------------------------
  // A team space where the humans cannot talk to each other is not one.
  db.exec(`
    CREATE TABLE IF NOT EXISTS messages (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      lobby_id      TEXT NOT NULL,
      author_user   TEXT NOT NULL,
      author_kind   TEXT NOT NULL DEFAULT 'human',
      body          TEXT NOT NULL,
      reply_to      INTEGER,
      mentions      TEXT,
      ref_object_id TEXT,
      ts            INTEGER NOT NULL,
      deleted       INTEGER NOT NULL DEFAULT 0,
      seq           INTEGER NOT NULL
    )
  `);
  db.exec('CREATE INDEX IF NOT EXISTS idx_messages_lobby_seq ON messages(lobby_id, seq)');

  // ---- file activity -> collision detection ------------------------------
  db.exec(`
    CREATE TABLE IF NOT EXISTS file_activity (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      lobby_id   TEXT NOT NULL,
      agent_id   TEXT NOT NULL,
      user_id    TEXT,
      path       TEXT NOT NULL,
      op         TEXT NOT NULL,
      ts         INTEGER NOT NULL
    )
  `);
  db.exec('CREATE INDEX IF NOT EXISTS idx_fa_lobby_path ON file_activity(lobby_id, path, ts)');

  migrate(db);
  seedSeq(db);
}

/**
 * Rebuild canvas_objects when it still carries the old single-column primary
 * key. SQLite cannot ALTER a primary key, so the table is recreated and copied.
 *
 * Guarded on the actual PK shape, so this runs at most once and is a no-op on a
 * database created after the fix.
 */
function rebuildCanvasObjectsPkIfNeeded(db: Database): void {
  const info = db.prepare('PRAGMA table_info(canvas_objects)').all() as any[];
  if (info.length === 0) return;

  const pkCols = info.filter((c) => c.pk > 0);
  if (pkCols.length >= 2) return;   // already composite

  db.exec('PRAGMA foreign_keys = OFF');
  const rebuild = db.transaction(() => {
    db.exec(`
      CREATE TABLE canvas_objects__new (
        id            TEXT NOT NULL,
        lobby_id      TEXT NOT NULL,
        type          TEXT NOT NULL,
        event_id      INTEGER,
        parent_id     TEXT,
        x             REAL NOT NULL DEFAULT 0,
        y             REAL NOT NULL DEFAULT 0,
        w             REAL NOT NULL DEFAULT 320,
        h             REAL NOT NULL DEFAULT 200,
        z             INTEGER NOT NULL DEFAULT 0,
        rotation      REAL NOT NULL DEFAULT 0,
        props         TEXT,
        version       INTEGER NOT NULL DEFAULT 1,
        version_nonce INTEGER NOT NULL DEFAULT 0,
        created_by    TEXT,
        updated_by    TEXT,
        updated_at    INTEGER NOT NULL,
        deleted       INTEGER NOT NULL DEFAULT 0,
        seq           INTEGER NOT NULL,
        PRIMARY KEY (lobby_id, id)
      )
    `);
    db.exec(`
      INSERT INTO canvas_objects__new
        (id, lobby_id, type, event_id, parent_id, x, y, w, h, z, rotation, props,
         version, version_nonce, created_by, updated_by, updated_at, deleted, seq)
      SELECT
         id, lobby_id, type, event_id, parent_id, x, y, w, h, z, rotation, props,
         version, version_nonce, created_by, updated_by, updated_at, deleted, seq
      FROM canvas_objects
    `);
    db.exec('DROP TABLE canvas_objects');
    db.exec('ALTER TABLE canvas_objects__new RENAME TO canvas_objects');
  });
  rebuild();
  db.exec('PRAGMA foreign_keys = ON');
  console.log('[schema] canvas_objects rebuilt with composite (lobby_id, id) primary key');
}

/**
 * Additive migrations. Every one is guarded, so this is safe to run on each
 * boot against a database that already holds real data.
 */
function migrate(db: Database): void {
  const cols = (table: string): string[] => {
    try {
      return (db.prepare(`PRAGMA table_info(${table})`).all() as any[]).map((c) => c.name);
    } catch {
      return [];
    }
  };
  const tableExists = (table: string): boolean => cols(table).length > 0;
  const addColumn = (table: string, col: string, ddl: string) => {
    if (!tableExists(table)) return;
    if (cols(table).includes(col)) return;
    db.exec(`ALTER TABLE ${table} ADD COLUMN ${col} ${ddl}`);
  };

  // Every block is guarded on the table existing. In the server these tables are
  // created before initSchema runs, but initSchema must also be safe to call on
  // its own — tests and the canvas modules do exactly that.

  // events join the seq ordering. Backfilled from `id`, which is already
  // monotonic, so historical rows keep their true relative order.
  if (tableExists('events')) {
    addColumn('events', 'seq', 'INTEGER');
    db.exec('CREATE INDEX IF NOT EXISTS idx_events_lobby_seq ON events(lobby_id, seq)');
    db.exec('UPDATE events SET seq = id WHERE seq IS NULL');
  }

  // annotations generalise from "comment on an event" to "comment on anything":
  // an event, a canvas object, or a bare point on the board.
  if (tableExists('annotations')) {
    addColumn('annotations', 'target_type',   "TEXT NOT NULL DEFAULT 'event'");
    addColumn('annotations', 'target_id',     'TEXT');
    addColumn('annotations', 'anchor_x',      'REAL');
    addColumn('annotations', 'anchor_y',      'REAL');
    addColumn('annotations', 'thread_parent', 'INTEGER');
    addColumn('annotations', 'resolved',      'INTEGER NOT NULL DEFAULT 0');
    addColumn('annotations', 'deleted',       'INTEGER NOT NULL DEFAULT 0');
    addColumn('annotations', 'seq',           'INTEGER');

    // Existing rows were all event comments; give them a target_id.
    db.exec("UPDATE annotations SET target_id = CAST(event_id AS TEXT) WHERE target_id IS NULL AND event_id IS NOT NULL");
    db.exec('UPDATE annotations SET seq = id WHERE seq IS NULL');
    db.exec('CREATE INDEX IF NOT EXISTS idx_ann_lobby_seq ON annotations(lobby_id, seq)');
    db.exec('CREATE INDEX IF NOT EXISTS idx_ann_target    ON annotations(target_type, target_id)');
  }

  // lobbies gain a per-lobby high-water mark so a client can ask "am I current?"
  addColumn('lobbies', 'last_seq', 'INTEGER NOT NULL DEFAULT 0');

  // Agent addressing and retry-safety. Added for databases created before the
  // columns were declared above; a no-op on fresh ones.
  addColumn('canvas_objects', 'handle', 'TEXT');
  addColumn('canvas_objects', 'idem_key', 'TEXT');
  if (tableExists('canvas_objects')) {
    db.exec('CREATE INDEX IF NOT EXISTS idx_co_handle ON canvas_objects(lobby_id, handle)');
    // Partial, so the many rows with no key do not all collide on NULL.
    db.exec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_co_idem
             ON canvas_objects(lobby_id, idem_key) WHERE idem_key IS NOT NULL`);
  }
}

/**
 * Seed the shared counter above every seq already in the database, so newly
 * issued numbers can never collide with backfilled historical ones.
 */
function seedSeq(db: Database): void {
  const row = db.prepare("SELECT value FROM counters WHERE name = 'seq'").get() as any;
  if (row) return;

  const highest = (table: string): number => {
    try {
      const r = db.prepare(`SELECT MAX(seq) AS m FROM ${table}`).get() as any;
      return r && r.m ? Number(r.m) : 0;
    } catch {
      return 0;
    }
  };

  const start = Math.max(
    highest('events'),
    highest('annotations'),
    highest('canvas_objects'),
    highest('messages'),
    0
  );
  db.prepare("INSERT INTO counters (name, value) VALUES ('seq', ?)").run(start);
}

/**
 * Take the next sequence number.
 *
 * Callers that write a row MUST take the number and insert the row inside the
 * same transaction, otherwise a concurrent reader can observe a gap and treat
 * it as "caught up" while a write is still in flight.
 */
export function nextSeq(db: Database): number {
  const row = db
    .prepare("UPDATE counters SET value = value + 1 WHERE name = 'seq' RETURNING value")
    .get() as any;
  return Number(row.value);
}

/** Current high-water mark without consuming a number. */
export function currentSeq(db: Database): number {
  const row = db.prepare("SELECT value FROM counters WHERE name = 'seq'").get() as any;
  return row ? Number(row.value) : 0;
}
